#version: "3.9"
services:
  # база данных
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flask_network

  # домашняя страница
  interface_service:
    restart: always
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - flask_network

  # парсер
  parser_service:
    restart: always
    build:
      context: .
      dockerfile: ./parser/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PYTHONPATH=/app:/parser:/
    depends_on:
      - db
    networks:
      - flask_network

  # ИИ модель
  ai_model_service:
    restart: always
    build:
      context: .
      dockerfile: ./ai_model/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - PYTHONPATH=/app:/ai_model:/
    depends_on:
      - db
    networks:
      - flask_network

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
#    depends_on:
#      - interface_service
#      - parser_service
#      - ai_model_service
#    networks:
#      - flask_network

volumes:
  postgres-data:

networks:
  flask_network:
#    driver: bridge
