services:
  # база данных
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flask_network

  # домашняя страница
  interface_service:
    restart: always
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./tools:/usr/local/lib/python3.9/site-packages/tools
      - ./status:/web_app/status
      - ./app/static:/web_app/app/static
      - ./app/templates:/web_app/app/templates
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - flask_network

  # парсер
  parser_service:
    restart: always
    build:
      context: .
      dockerfile: ./parser/Dockerfile
    volumes:
      - ./status:/web_app/status
      - ./tools:/usr/local/lib/python3.9/site-packages/tools
    environment:
      - PYTHONPATH=/web_app:/parser:/
    depends_on:
      - db
    networks:
      - flask_network

  # ИИ модель
  ai_model_service:
    restart: always
    build:
      context: .
      dockerfile: ./ai_model/Dockerfile
    volumes:
      - ./status:/web_app/status
      - ./tools:/usr/local/lib/python3.9/site-packages/tools
    environment:
      - PYTHONPATH=/web_app:/ai_model:/
    depends_on:
      - db
    networks:
      - flask_network


volumes:
  postgres-data:

networks:
  flask_network:
