services:
  # база данных
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flask_network

  # домашняя страница
  interface_service:
    restart: always
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app/static:/web_app/app/static
      - ./app/templates:/web_app/app/templates
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - flask_network

  # парсер
  parser_service:
    restart: always
    build:
      context: .
      dockerfile: ./parser/Dockerfile
    volumes:
      - ./parser/static:/web_app/parser/static
      - ./parser/templates:/web_app/parser/templates
    ports:
      - "5001:5001"
    environment:
      - PYTHONPATH=/web_app:/parser:/
    depends_on:
      - db
    networks:
      - flask_network

  # ИИ модель
  ai_model_service:
    restart: always
    build:
      context: .
      dockerfile: ./ai_model/Dockerfile
    volumes:
      - ./ai_model/static:/web_app/ai_model/static
      - ./ai_model/templates:/web_app/ai_model/templates
    ports:
      - "5002:5002"
    environment:
      - PYTHONPATH=/web_app:/ai_model:/
    depends_on:
      - db
    networks:
      - flask_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"  # Основной конфиг
      - "./app/static:/web_app/app/static"             # Статика interface_service
      - "./parser/static:/web_app/parser/static"       # Статика parser_service
      - "./ai_model/static:/web_app/ai_model/static"   # Статика ai_model_service
    depends_on:
      - interface_service
      - parser_service
      - ai_model_service
    networks:
      - flask_network

volumes:
  postgres-data:

networks:
  flask_network:
