version: "3.9"
services:
  # база данных
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"

  parser_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parser_service
    ports:
      - "5001:5000"
    depends_on:
      - db

  interface_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interface_service
    ports:
      - "5002:5000"

  ai_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_service
    ports:
      - "5003:5000"
    depends_on:
      - db


#version: '3.8'
#services:
#  postgres_db:
#    container_name: 'postgres_db'
#    image: postgres:13.0-alpine
#    ports:
#      - '5432:5432'
#    env_file: .db.env
#    networks:
#      - db_network
#  app:
#    container_name: app
#    restart: always
#    env_file: .env
#    build:
#      context: .
#      dockerfile: Dockerfile
#    networks:
#      - db_network
#      - web_network
#    volumes:
#      - ./:/usr/src/app
#    depends_on:
#      - postgres_db
#  nginx:
#    container_name: nginx
#    restart: always
#    image: nginx:latest
#    ports:
#      - "5085:5085"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    networks:
#      - web_network
#    depends_on:
#      - app
#networks:
#  db_network:
#    driver: bridge
#  web_network:
#    driver: bridge